### ISSUE TITLE
No Apps in App-Switcher in 0.0.7

### ISSUE THREAD

**Issue by warmup72** [Celve/Peninsula#31]
After installing 0.0.7 the App-Switcher ist empty on my macOS 14.7.2
Switching back to 0.0.6

**Comment by Celve** [comment]
I think you should regrant the accessibility permission for Peninsula. It might because I have notarized the app. 
For regranting, you could: 
1. Open **Settings**
2. Open **Privacy & Security**
3. Open **Accessibility**
4. Delete Peninsula
5. Reopen v0.0.7
6. Check **Accessibility** again, Peninsula will be there
7. Grant permission for Peninsula
8. Then reopen Peninsula again and I believe apps will be there.

**Comment by warmup72** [comment]
After granting permission I can see the open Applications but cmd-tab doesn´t work anymore. CMD-tab now open the build in app-switcher

**Comment by Celve** [comment]
Can you restart Peninsula to see whether cmd-tab works?

**Comment by warmup72** [comment]
Sorry, it must have been my Mac. After reassigning the rights and a reboot, 0.0.7 works
